severity: low
exclude:
  - message: Codacy project public id
    pattern: a73118d332724935930464a45c9da3cc

  - message: Sourcemaps
    pattern: sourceMappingURL=data:application/json;base64,

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Dependencies
    paths:
      - package-lock.json
      - node_modules
      - venv
      - yarn-error.log
      - yarn.lock
